languaje: java
branches:
  - /^release-[0-999].[0-999]$/
  - master
notifications:
  email:
    recipients:
      - antonio@gonzalez.cr
script:
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify
    #SONARCLOUD
  - mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=antgonto -Dsonar.login=$SONAR